name: Server Map Checker

on:
  schedule:
    - cron: '*/5 * * * *'   # Trigger every 5 minutes
  workflow_dispatch: {}       # Allow manual trigger

jobs:
  check-map:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      # Comma-separated list of allowed map names (without numeric suffix)
      ALLOWED_MAPS: "de_train,de_nuke,de_inferno,de_cbble,de_cpl_mill,de_mirage,de_tuscan,de_aztec"
      # Comma-separated list of servers in the format "name;IP;PORT"
      SERVERS: ${{ vars.SERVERS }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Needed to use 'gh' CLI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo curl -sfLo /usr/bin/a2s-cli https://github.com/WoozyMasta/a2s/releases/latest/download/a2s-cli-linux-amd64
          sudo chmod +x /usr/bin/a2s-cli
          gh auth setup-git

      - name: Check server maps and send notifications if changed
        run: |
          # Convert comma-separated SERVERS into an array
          IFS=',' read -ra SERVER_LIST <<< "$SERVERS"
          for SERVER in "${SERVER_LIST[@]}"; do
            # Split each server definition into name, IP, and PORT
            IFS=';' read -ra FIELDS <<< "$SERVER"
            NAME="${FIELDS[0]}"
            IPPORT="${FIELDS[1]}"
            
            echo "Checking server: $NAME at $IPPORT"
            # Retrieve current map info using a2s-cli and extract the 'map' value with jq
            JSON_OUTPUT=$(a2s-cli -j info "$IPPORT")
            CURRENT_MAP=$(echo "$JSON_OUTPUT" | jq -r '.map')
            PLAYERS=$(echo "$JSON_OUTPUT" | jq -r '"\(.players)/\(.max_players)"')
            echo "Current map: $CURRENT_MAP"
            echo "Players: $PLAYERS"
            
            # Get previous map using GitHub CLI
            PREVIOUS_MAP=$(gh variable get "MAP_${NAME}" --repo ${{ github.repository }} || echo "")

            # Store current map in GitHub Actions variables
            gh variable set "MAP_${NAME}" --body "$CURRENT_MAP" --repo ${{ github.repository }}            
            
            # Check allowed maps by looping over each allowed map pattern
            MATCHED=0
            for ALLOWED in $(echo "$ALLOWED_MAPS" | tr ',' '\n'); do
              if echo "$CURRENT_MAP" | grep -q "$ALLOWED"; then
                MATCHED=1
                break
              fi
            done
            
            if [ $MATCHED -eq 1 ]; then
              if [[ -n "$PREVIOUS_MAP" && "$CURRENT_MAP" != "$PREVIOUS_MAP" ]]; then
                MESSAGE="Server $NAME changed to map: $CURRENT_MAP ($PLAYERS)"
                echo "Sending notification: $MESSAGE"
                curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                     -d chat_id="${TELEGRAM_CHAT_ID}" \
                     -d text="$MESSAGE"
              else
                echo "Map unchanged. No notification sent."
              fi
            else
              echo "Map $CURRENT_MAP is not in allowed list. No notification sent."
            fi
          done
